### ISSUE TITLE
Renaming the repository

### ISSUE THREAD

**Issue by EmanueleMinotto** [teamed/teamed.github.io#15]
By renaming the repository to `teamed.github.io` you should be able tu use [default GitHub settings for pages](https://help.github.com/articles/user-organization-and-project-pages/) and prevent this problem: http://teamed.github.io/teamed.io/

**Comment by EmanueleMinotto** [comment]
ping @yegor256

**Comment by yegor256** [comment]
@EmanueleMinotto fixed. many thanks!
